title: testing-learning-lab
description: testing learning lab
template:
  repo: testing-learning-lab-template
  name: testing-learning-lab
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
